// <auto-generated />
using System;
using AppVideoGameAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppVideoGameAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240809225722_FirstInsrimentoDati")]
    partial class FirstInsrimentoDati
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppVideoGameAPI.Models.CasaProduttrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CaseProduttrici");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Insomniac Games"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Sony"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Nintendo"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Microsoft"
                        });
                });

            modelBuilder.Entity("AppVideoGameAPI.Models.Console", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Consoles");
                });

            modelBuilder.Entity("AppVideoGameAPI.Models.DataUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("IndirizzoUtente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UltimoAccesso")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "9aeca00b-ab93-480e-9b9f-5babf2324102",
                            AccessFailedCount = 0,
                            Cognome = "Sartini",
                            ConcurrencyStamp = "3aaec84c-29ff-4a80-ae31-39ad5016aa0e",
                            Email = "fabiansartini@gmail.com",
                            EmailConfirmed = true,
                            IndirizzoUtente = "Via Pragelato 20",
                            LockoutEnabled = false,
                            Nome = "Fabian",
                            NormalizedEmail = "FABIANSARTINI@GMAIL.COM",
                            NormalizedUserName = "FABIANSARTINI@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEjbSLD8IunEWp4cfOlkqTY1b8sRfjJdCWLHsGLKpDvyVwwgjvaJ8WKdP2y2p/TlEA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "908313fb-fcf4-42d4-a0a2-c8bac420869b",
                            TwoFactorEnabled = false,
                            UserName = "fabiansartini@gmail.com"
                        },
                        new
                        {
                            Id = "4d70d07d-b48d-4e09-95f5-da9acd4cc3fd",
                            AccessFailedCount = 0,
                            Cognome = "Sartini",
                            ConcurrencyStamp = "3ead14ae-5fe0-474c-9620-64da25094bc4",
                            Email = "spaceplayer98@gmail.com",
                            EmailConfirmed = true,
                            IndirizzoUtente = "Via Russo 238",
                            LockoutEnabled = false,
                            Nome = "Fabian",
                            NormalizedEmail = "SPACEPLAYER98@GMAIL.COM",
                            NormalizedUserName = "SPACEPLAYER98@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEHa4uDaRQTByFxp4DTNxrBVVzcM793XrENeIrsaAUmUY9kRw1hNXOhguM+9GK92/vw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b6cbd5ae-96f9-4072-bf27-287673e0ae09",
                            TwoFactorEnabled = false,
                            UserName = "spaceplayer98@gmail.com"
                        });
                });

            modelBuilder.Entity("AppVideoGameAPI.Models.FormatoGioco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Formati");
                });

            modelBuilder.Entity("AppVideoGameAPI.Models.Funzionalita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VideoGiocoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VideoGiocoId");

                    b.ToTable("Funzionalitas");
                });

            modelBuilder.Entity("AppVideoGameAPI.Models.Genere", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Generi");
                });

            modelBuilder.Entity("AppVideoGameAPI.Models.ItemOrdine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrdineId")
                        .HasColumnType("int");

                    b.Property<short>("Quantita")
                        .HasColumnType("smallint");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrdineId");

                    b.HasIndex("StockId");

                    b.ToTable("ItemOrdini");
                });

            modelBuilder.Entity("AppVideoGameAPI.Models.LivelloRichiestoPC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LivelliRichiestiPC");
                });

            modelBuilder.Entity("AppVideoGameAPI.Models.Ordine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("UtenteId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UtenteId");

                    b.ToTable("Ordini");
                });

            modelBuilder.Entity("AppVideoGameAPI.Models.Recensione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("VideoGiocoId")
                        .HasColumnType("int");

                    b.Property<short>("Voto")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VideoGiocoId");

                    b.ToTable("Recensioni");
                });

            modelBuilder.Entity("AppVideoGameAPI.Models.RequisitiPC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Audio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CPU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LivelloRichiestoId")
                        .HasColumnType("int");

                    b.Property<string>("OS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Processore")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RAM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchedaGrafica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VideoGiocoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LivelloRichiestoId");

                    b.HasIndex("VideoGiocoId");

                    b.ToTable("RequisitiPCs");
                });

            modelBuilder.Entity("AppVideoGameAPI.Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConsoleId")
                        .HasColumnType("int");

                    b.Property<int>("FormatoGiocoId")
                        .HasColumnType("int");

                    b.Property<short>("Quantita")
                        .HasColumnType("smallint");

                    b.Property<int>("VideoGiocoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConsoleId");

                    b.HasIndex("FormatoGiocoId");

                    b.HasIndex("VideoGiocoId");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("AppVideoGameAPI.Models.VideoGioco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CasaProduttriceId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("DataRilascio")
                        .HasColumnType("date");

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CasaProduttriceId");

                    b.ToTable("VideoGiochi");
                });

            modelBuilder.Entity("ConsoleVideoGioco", b =>
                {
                    b.Property<int>("ConsolesId")
                        .HasColumnType("int");

                    b.Property<int>("VideoGiochiId")
                        .HasColumnType("int");

                    b.HasKey("ConsolesId", "VideoGiochiId");

                    b.HasIndex("VideoGiochiId");

                    b.ToTable("ConsoleVideoGioco");
                });

            modelBuilder.Entity("GenereVideoGioco", b =>
                {
                    b.Property<int>("GeneriId")
                        .HasColumnType("int");

                    b.Property<int>("VideoGiochiId")
                        .HasColumnType("int");

                    b.HasKey("GeneriId", "VideoGiochiId");

                    b.HasIndex("VideoGiochiId");

                    b.ToTable("GenereVideoGioco");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "9aeca00b-ab93-480e-9b9f-5babf2324102",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "4d70d07d-b48d-4e09-95f5-da9acd4cc3fd",
                            RoleId = "1"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AppVideoGameAPI.Models.Funzionalita", b =>
                {
                    b.HasOne("AppVideoGameAPI.Models.VideoGioco", "VideoGioco")
                        .WithMany("Funzionalitas")
                        .HasForeignKey("VideoGiocoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VideoGioco");
                });

            modelBuilder.Entity("AppVideoGameAPI.Models.ItemOrdine", b =>
                {
                    b.HasOne("AppVideoGameAPI.Models.Ordine", "Ordine")
                        .WithMany("ItemOrdini")
                        .HasForeignKey("OrdineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppVideoGameAPI.Models.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ordine");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("AppVideoGameAPI.Models.Ordine", b =>
                {
                    b.HasOne("AppVideoGameAPI.Models.DataUser", "DataUser")
                        .WithMany()
                        .HasForeignKey("UtenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DataUser");
                });

            modelBuilder.Entity("AppVideoGameAPI.Models.Recensione", b =>
                {
                    b.HasOne("AppVideoGameAPI.Models.DataUser", "Utente")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppVideoGameAPI.Models.VideoGioco", "VideoGioco")
                        .WithMany()
                        .HasForeignKey("VideoGiocoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Utente");

                    b.Navigation("VideoGioco");
                });

            modelBuilder.Entity("AppVideoGameAPI.Models.RequisitiPC", b =>
                {
                    b.HasOne("AppVideoGameAPI.Models.LivelloRichiestoPC", "LivelloRichiesto")
                        .WithMany()
                        .HasForeignKey("LivelloRichiestoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppVideoGameAPI.Models.VideoGioco", "VideoGioco")
                        .WithMany()
                        .HasForeignKey("VideoGiocoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LivelloRichiesto");

                    b.Navigation("VideoGioco");
                });

            modelBuilder.Entity("AppVideoGameAPI.Models.Stock", b =>
                {
                    b.HasOne("AppVideoGameAPI.Models.Console", "Console")
                        .WithMany()
                        .HasForeignKey("ConsoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppVideoGameAPI.Models.FormatoGioco", "Formato")
                        .WithMany()
                        .HasForeignKey("FormatoGiocoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppVideoGameAPI.Models.VideoGioco", "VideoGioco")
                        .WithMany()
                        .HasForeignKey("VideoGiocoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Console");

                    b.Navigation("Formato");

                    b.Navigation("VideoGioco");
                });

            modelBuilder.Entity("AppVideoGameAPI.Models.VideoGioco", b =>
                {
                    b.HasOne("AppVideoGameAPI.Models.CasaProduttrice", "CasaProduttrice")
                        .WithMany()
                        .HasForeignKey("CasaProduttriceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CasaProduttrice");
                });

            modelBuilder.Entity("ConsoleVideoGioco", b =>
                {
                    b.HasOne("AppVideoGameAPI.Models.Console", null)
                        .WithMany()
                        .HasForeignKey("ConsolesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppVideoGameAPI.Models.VideoGioco", null)
                        .WithMany()
                        .HasForeignKey("VideoGiochiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GenereVideoGioco", b =>
                {
                    b.HasOne("AppVideoGameAPI.Models.Genere", null)
                        .WithMany()
                        .HasForeignKey("GeneriId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppVideoGameAPI.Models.VideoGioco", null)
                        .WithMany()
                        .HasForeignKey("VideoGiochiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AppVideoGameAPI.Models.DataUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AppVideoGameAPI.Models.DataUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppVideoGameAPI.Models.DataUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AppVideoGameAPI.Models.DataUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AppVideoGameAPI.Models.Ordine", b =>
                {
                    b.Navigation("ItemOrdini");
                });

            modelBuilder.Entity("AppVideoGameAPI.Models.VideoGioco", b =>
                {
                    b.Navigation("Funzionalitas");
                });
#pragma warning restore 612, 618
        }
    }
}
